name: CI

on: push

jobs:
  deploy-to-embedded:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('deploy_requirements.txt') }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r deploy_requirements.txt

      - name: Deploy
        run: |
          rshell -f deploy_cmds.rsh
